# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            AI4CSS @ ICDM 2025
tagline:          'AI for Computational Social Science'
description:      'Workshop on Artificial Intelligence for Computational Social Science at the 2025 IEEE International Conference on Data Mining (ICDM).'
url:              https:/macss-project.github.io
baseurl:          '/ai4css2025'  # Base URL for your site
                  # Set to the subdirectory you’ll publish under (e.g., "/ai4css2025")

author:
  name:           'AI4CSS Organizing Committee'
  url:            https://icdm2025.org

# paginate:         5
# paginate_path:    '/posts/page/:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/posts'

# Comment system (disable unless needed)
disqus:
  shortname:      ""  # Leave blank or remove to disable

# Google Analytics (replace with your own tracking ID or remove)
google_analytics: ""
